---
title: Comparing the Best Markup Languages for Making PDF Documents
author: ~
date: '2022-05-11'
slug: comparing-the-best-markup-languages-for-making-pdf-documents
categories: []
tags: []
---

PDF is rightfully the standard output format for documents.
All word processors can output to PDF, but it is difficult to convert PDF to files word processors can edit.
Most people use "what you see is what you get" word processors like Microsoft Word, Google Docs, or LibreOffice Writer.
This type of word processor is convenient but it is also limited and unprofessional.
It is easier to get into, but it is harder to use in the long run.
This is the problem with all "what you see is what you get" programs: they do not follow the "[separation of content and presentation](https://en.wikipedia.org/wiki/Separation_of_content_and_presentation)" design principle.


Markup word processors are practical and professional alternatives.
However, there are so many of them and all of them are different.
It can be tirelessly difficult to choose the correct one.
It took me a surprisingly long time to choose the correct one for my uses.
And it took me even more time to create [the proper templates](https://github.com/amarakon/amaryaml) for easier use.
