baseURL = "https://amarakon.github.io/"
languageCode = 'en-ca'
title = "Amarakon’s Website"
theme = "hugo-cream"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "nord"
guessSyntax = false
[markup.tableOfContents]
startLevel = 1
endLevel = 3

[security]
enableInlineShortcodes = true

[menu]
[[menu.pages]]
name = "About"
url = "/about/"
[[menu.pages]]
name = "Programs"
url = "/programs/"
[[menu.pages]]
name = "Projects"
url = "/projects/"
[[menu.pages]]
name = "Articles"
url = "/articles/"

[[menu.links]]
name = "GitHub"
url = "https://github.com/amarakon"
[[menu.links]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCbZc671K2NxNbr1Kfqz6Fmg"
