---
title: Vim Sensible AutoComp
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

# Introduction

https://github.com/amarakon/vim-sensible-autocomp

This is yet another auto-completion plugin for Vim.
At this point, there are probably hundreds.
So I will explain what makes mine stand out from the rest.
The main reason I wrote this plugin is that I wanted an auto-completion plugin
written purely in Vim script or Lua.
I hate seeing a cool plugin and then finding out its written in Python.
Not only will that make the plugin slower and more bloated, but installing it
and setting it up will be such a hassle that it is not worth it.

Vim already has built-in functionality for completion menus.
Not using that is like reinventing the wheel.
But I just want automatic suggestions as I type, and they have to be reasonable
suggestions.
They should be things that I would actually select.
And it should work for every programming language.

Basically, what this plugin does is just make suggestions for omni-completion
and keywords in the current file if you are typing any letter.
If you type the location to a directory or file, it will automatically complete
that as well.
Most other suggestions are complete unnecessary.
And I implemented this in less than 20 lines of code.

# Dependencies

- [VimCompletesMe](https://github.com/ackyshake/VimCompletesMe)

# Installation

## Vim

```shell
git clone https://github.com/amarakon/vim-sensible-autocomp ~/.vim/pack/vendor/start/vim-sensible-autocomp
```


## Neovim

```shell
git clone https://github.com/amarakon/vim-sensible-autocomp ~/.local/share/nvim/site/pack/default/start/vim-sensible-autocomp
```
