---
draft: true
title: Gentoo Linux Should be Approved by the Free Software Foundation
author: ~
date: '2022-05-05'
slug: gentoo-linux-should-be-approved-by-the-free-software-foundation
categories: ["Operating Systems"]
tags: ["foss", "fsf"]
bibliography: ../../../static/bibliography.bib
csl: ../../../static/citations/apa-no-initials.csl
link-citations: true
reference-section-title: References
---

Gentoo Linux is a 100% free operating system.
All of its source code is publicly available on GitHub, meaning that it's open-source.
It is licensed under a free license: GNU General Public License Version 2.
It does not include any preinstalled proprietary software.
Its package manager, Portage, blocks proprietary software against the user's will by default.
All of these reasons prove that is a completely free operating system that is against the use of proprietary software, so it should be in the Free Software Foundation's (FSF) [list of free Linux distributions](https://www.gnu.org/distros/free-distros.en.html).

# Free System Distribution Guidelines [@gnu-fsdg]

The GNU free system distribution guidelines (GNU FSDG) is an article supported by the FSF.
It includes the guidelines that a distribution must follow in order to be endorsed by the FSF.
Gentoo Linux easily follows these guidelines and I will prove it.

## Complete distributions

## License rules

## Non-free firmware

## Non-functional data

## Trademarks

## Documentation

## Patents

## No malware

## Commitment to correct mistakes

## Maintenance

## Name confusion

## Contacting upstream if you are downstream

## Please teach users about free software

## Please avoid repeating propaganda and confusion

# Free Software Foundation's Justification

The Free Software Foundation justifies not including Gentoo Linux on their list of free Linux distributions with the following short statement:

> Gentoo includes installation recipes for a number of nonfree programs in its primary package system.
