---
title: Cfetch
date: "`r format(Sys.time(), '%Y-%m-%d')`"
---

Cfetch is a suckless-like command-line system information tool.
It displays information about your operating system, kernel, packages, and more along with ASCII art of your operating system in an elegant way.
The purpose of Cfetch is to quickly get information about everything quickly instead of using one different program for getting each piece of information.
[Neofetch](https://github.com/dylanaraps/neofetch) does a poor job at this because it is extremely slow because it is written in Bash, so the purpose of Neofetch is just for screenshots.
Despite this, Cfetch still looks more pleasing than Neofetch does.
Cfetch is a rewrite of Neofetch in C forked from [JaGoLi/paleofetch](https://github.com/JaGoLi/paleofetch) which was forked from [ss7m/paleofetch](https://github.com/ss7m/paleofetch).

**Disclaimer:** Cfetch is still in very early development.
I am currently learning more about how to program in C and I will return to this project later.
Stay tuned for that.

# Usage

Simply run the executable:

```shell
cfetch
```

By default, `cfetch` will cache certain  information (in `$XDG_CACHE_HOME/cfetch`)
to speed up subsequent calls. To ignore the contents of the cache (and repopulate it), run the following:

```shell
cfetch --recache
```

The cache file can safely be removed at any time, Cfetch will repopulate it if it is absent.

# Dependencies

1. xorg-server
1. libX11
1. libpci

## Universal

```shell
`# user` git clone https://github.com/amarakon/cfetch
`# user` cd cfetch
`# user` make install
```

## Gentoo

```shell
`# root` eselect repository add amarlay git https://github.com/amarakon/amarlay
`# root` emerge --sync amarlay
`# root` emerge app-misc/cfetch
```

# Uninstallation

## Universal

```shell
`# user` cd cfetch
`# root` make uninstall
```

## Gentoo

```shell
`# root` emerge -c app-misc/cfetch

# Remove my overlay (optional)
`# root` eselect-repository remove -f amarlay
`# root` emerge --sync
```

# Configuration

Being a suckless-like program, Cfetch is configured by editing `config.h` and recompiling.
You can change your logo by including the appropriate header file in the logos directory.
The color with which Cfetch draws the logo can be chosen by defining the `COLOR` macro,
look up ANSI escape codes for information on customizing this.

The last configuration is the `CONFIG` macro, which controls what information Cfetch 
prints. Each entry in this macro should look like

```c
/* Name        Function            Cache */
{ "NAME: ",    getter_function,    false },\
```
    
Take note of the trailing comma and backslash. The first piece, `"NAME: "`, sets
what Cfetch prints before printing the information; this usually tells you what
bit of information is being shown. Note that the name entry should be unique for entries
which are to be cached. The second piece, `getter_function`, sets
which function Cfetch will call display. Current available getter functions are

* `get_title`: prints `host@user` like in a bash prompt. Host and user will be printed in color.
* `get_bar`: Meant to be added after `get_title`, underlines the title
* `get_os`: Prints your operating system (including distribution)
* `get_host`: Prints the model of computer
* `get_kernel`: Prints the version of the linux kernel
* `get_uptime`: Shows how long linux has been running
* `get_packages`: Shows how many packages you have installed. Currently only works for pacman.
* `get_shell`: Shows which shell you are using
* `get_resolution`: Prints your screen resolution
* `get_terminal`: Prints the name of your current terminal
* `get_cpu`: Prints the name of your CPU, number of cores, and maximum frequency
* `get_gpu1`, `get_gpu2`: Print the GPU on your system. If you don't have both integrated graphics and an external GPU, `get_gpu2` will likely be blank
* `get_gpu`: (Tries to) print your current GPU
* `get_colors1`, `get_colors2`: Prints the colors of your terminal

To include a blank line between entries, put `SPACER \` between the two lines
you want to separate.

The booleans in `CONFIG` tell Cfetch whether you want to cache an entry.
When cached, Cfetch will save the value and not recompute it whenever you run Cfetch. 
(unless you specify the `--recache` option).

The CPU and GPU name can be configured as well. This is done under the CPU_CONFIG and GPU_CONFIG section
in the config.h file. Two macros are provided to customize and tidy up the model names:

* `REMOVE(string)`: removes the first occurence of `string`
* `REPLACE(string1, string2)`: replaces the first occurence of `string1` with `string2`

Don't forget to run Cfetch with the `--recache` flag after compiling it with your new
configuration, otherwise it will still show the old name for already cached entries.
