---
title: Why You Should Pay Attention to Your Choice of Software
author: ~
date: '2022-04-30'
slug: why-you-should-pay-attention-to-your-choice-of-software
categories: []
tags: []
output: md_document
---

# Introduction
What I've noticed about many subjects in life is that many people just want to be sheep.
Notice how I said "want to be sheep" and not "are sheep."
That's because my emphasis is on the fact that people are choosing to be ignorant.
This is true in many cases, especially in politics and computing.
In this post, I will be focusing on computing.
I want to clarify by saying that I think there is nothing wrong with being ignorant, but it is wrong to be willfully ignorant.

I remember a couple of years ago I was a very different person than I am today.
I was a textbook example of a [normie](https://www.urbandictionary.com/define.php?term=Normie).
I would use pretty much the same software everybody else was using.
My operating system was Windows 10, my music player was Spotify.
There is nothing morally wrong with being that way, but when you're a normie, it is extremely easy to be influenced and taken advantage of.
You follow what everybody else was doing regardless if it's good or bad.

# Change
One day, I was scrolling through YouTube and I found something that intrigued me.
It was a video of somebody comparing 3D rendering on Windows 10 to GNU/Linux.
I was extremely surprised by how much GNU/Linux is blatantly better than Windows 10.
For the next couple of weeks, I experimented with GNU/Linux without much success.
I found it extremely difficult to get basic things done, like connecting to WiFi.
Could it be that the normie lifestyle is correct and that alternatives are terrible most of the time?

I almost gave up, but since I've come so far, I kept using GNU/Linux.
I eventually solved my main issues with it.
I spent the next couple of months experimenting with it and mastering it.
During that time, I increasingly learned the evils of common software and how everybody, including myself, fell for that trap.
I learned how the programs we use are brainwashing us.
This is not an exaggeration in the slightest.

# Problem
There is a tiny list of programs that people tend to use.
It is surprising how small that list is and how it is still shrinking.
There is not much diversity of thought when it comes to things like this.
That's my point.
That's what I'm getting at with this post.

Not only was I much more free literally by changing my choice of software, but I was free in my thinking as well.
I could do things that I never could do before, and I understood things that I've always wanted to understand.
It is impossible for me to explain it to you, it is something you must experience for yourselves.
The easiest way to explain it is this; technology companies want their users to be ignorant, it benefits them.
They want to be the geniuses making the complex programs that they would never use themselves, while you are the incompetent user.
They do not want **you** to be in control.

This is evident when you find out that all tech billionaires are extremely strict about technology use.
They want you to be a slave to their evil technology that you do not understand.
But they do not want their kids to be, because those are just about the only people they truly care about.
They know that if you did understand their technology, you would hesitate using it.
If you did know that one company literally influences what you know and think about literally everything and which political ideology you support, Google would know that you would hesitate using their search engine.
If you did know that your smartphone has devastating affects on your brain and mental health, smartphone companies would know that you would hesitate buying their products.
I could go on and on with examples to prove that almost every single piece of technology we use today is problematic at least and simply evil at most.

# Solution
To return to the first point I made, there is nothing wrong with being ignorant, but there is plenty of wrong with being willfully ignorant.
I believe that most people are willfully ignorant to these facts.
Most people would react to this the exact same way.
First, they deny it.
Then, once you prove it to them, they will justify it with bad excuses.
They will pretend like there's nothing wrong with literally every major social media company banning the president of the United States at the exact same time.
They will pretend like there's nothing wrong with your data being collected and used to control you.
The underlying motivation for these denials and justifications is to hide from reality.
Because they know that these things are wrong, but they do not want to take any action.
Understandably, most people do not want to drastically change their current lifestyle.

However, once you stop denying the corrupted reality and start embracing alternative software, you will realize just how much more free you will become.
You will be able to do things you never could before.
It can benefit your intelligence, your productivity, and much more.
People have called me weird and a 'conspiracy theorist' for my beliefs.
But I know that since my beliefs are grounded in the truth and morality, I will never feel shame for them.

Just like how in a democratic government, the people should control the government and not the other way around, the users should control tech companies and not the other way around.
This is only possible by paying close attention to software licenses, free versus proprietary software, digital rights management, and other important subjects concerning freedom and software.
Choose the best options based on those.
You should also be extremely picky—because just like politicians, tech companies tend to be corrupt.
**You should pay attention to your choice of software so that you could finally have the computing freedom that you deserve.**
