---
draft: true
title: You Should Prefer Command-Line Software
author: ~
date: '2022-05-07'
slug: you-should-prefer-command-line-software
categories: ["Technology"]
tags: ["cli"]
bibliography: ../../../static/bibliography.bib
csl: ../../../static/citations/apa-no-initials.csl
link-citations: true
reference-section-title: References
---

There are many benefits of preferring command-line software over graphical software.
Graphical User Interfaces generally promote lazy thinking. 
Command-line interfaces generally promote critical thinking.
I think it is unfortunate that most people have not even heard of command-line software.
Whenever I would be doing my work in school by running commands, most people who pass by would assume that I am coding.
This is obviously because they have not used command-line programs, so their view of a dark terminal window and fast typing of commands they do not understand leads them to this conclusion.
That then leads them to the conclusion that anything other than a modern graphical "app" is too difficult for them.
This is why most people do not use command-line software.

In order to efficiently use computers, you need to get rid of this mindset.

# Unix Philosophy

> This is the Unix philosophy:
Write programs that do one thing and do it well.
Write programs to work together.
Write programs to handle text streams, because that is a universal interface.  
>  
— Ken Thompson

Graphical programs do not follow any of these three rules of the Unix philosophy.
The Unix philosophy is important because it outlines the criteria software needs to be considered good.
Command-line programs follow the Unix philosophy most of the time, hence they are good most of the time
Critics of the Unix philosophy argue that "the user interface is horrid" [@the-truth-about-unix].
Truthfully, Unix's user interface is amazing.
Command-line interfaces are simpler and easier to understand than graphical ones.
They are just not dumbed down for stupid people.

## Do one thing and do it well

Programs should do one thing and do it well because programs are otherwise bloated.
Bloated programs are ones that are too large in their code-base.
They tend to be slower than they are supposed to be because they are trying to fulfill more than one purpose.
Each program should serve one purpose, that is why there is more than one program.
If the program doesn't serve one and only one main purpose, the program is too versatile.
"Worse is better" seems like a contradictory statement by Richard Gabriel, but what it really means is that certain things may sound worse on paper, but truly are better in practice.
One such example is a less versatile program.

## Work together

Another reason programs should do one thing and do it well is that they should work together.
Instead of having one big program that does everything, have many small programs that do one thing well and work together.
This is the main difference between command-line and graphical programs.
Command-line programs naturally work well together using pipes; you can pipe the output of one command to another.
Each command-line program is small but has its own unique purpose, and they all use the same interface so they should be expected to always work together.
Graphical programs on the other hand, cannot naturally work well together because they are large and versatile.
A graphical program can only be used by itself because its interface is unique to itself.

To give two easy-to-understand examples, I will compare Windows to GNU.
Windows is primarily graphical.
It does have the powershell but no one uses it.
As a result of using primarily graphical software, Windows is a huge operating system.
It cannot even run smoothly on most old computers.
The GNU core utilities are the opposite of Windows.
GNU is tiny because it is comprised of small command-line programs that do one thing well and work together.

## Handle text streams

Unlike graphical user interfaces, text streams are a universal interface.
This means that all programs use text streams.
Programs should handle text streams directly and efficiently, that should be their main focus.
Obviously, all command-line programs handle standard input and standard output within the terminal.
However, graphical programs only handle text streams within the graphical user interface.
It is impossible to pipe the output of a command into that of another in a graphical user interface because it does not handle text streams directly.

# Easier to Use

It may not seem like it, but command-line software is easier to use than graphical software.
All command-line programs work the same way, while all graphical programs work differently.
For each graphical program you use, you will have to learn the user interface.
If you do not know how to use it, you will painfully have to search how to do so online.
This is one of the reasons why most people only use an extremely limited diversity of software.
For each command-line program you use, you might not even have to do anything new at all.
Most of them have very similar options to do the same thing.

If you need help with a command-line program, getting help is always easy.
Most of them have a help flag (usually `--help` and `-h`).
For example: to get help with the `awk` command, all you have to do is run `awk --help` or `awk -h`.
For more detailed help, you can read the manual page instead, using the `man` command.
For example: to read `awk`'s man page, run `man awk`.
To search for man pages, you have to run `mandb` (as root) for the first time.
After you have updated the database, simply run `apropos .`.

# Easier to Write

Not only is command-line software easier to use, it is also easier to write.
In [my previous post](/amarakon.com/blog/programming-is-invaluable-for-everyone/), I explained why programming is invaluable for everyone.
Writing graphical software is extremely difficult as you need a lot of experience to do so.
Writing command-line software is surprisingly easy because you will have experience with using them.
If you favor open-source software—which you should, you can not only write your own unique programs, but also modify existing programs.
This will help you optimize your workflow and make you more efficient with computers.
Graphical programs are not only closed-source, but even when they are open-source, their code-base is huge and not legible for most people.

# Conclusion

To conclude, I want to clarify that I am not against graphical user interfaces.
The purpose of this point is to prove that you should **favor** command-line software, you should not use it to **replace** all graphical software.
Command-line software should be used most of the time, especially when the task is simple.
Graphical software should be used when absolutely necessary.
You should never render three-dimensional models using the command-line.
Similarly, you should never use a command-line web browser.
