---
title: Should You Disallow Your Kid to Have a Smartphone
date: "2022-05-16"
slug: should-you-disallow-your-kid-to-have-a-smartphone
tags: ["family", "phones"]
bibliography: ../../../static/bibliography.bib
csl: ../../../static/citations/apa-no-initials.csl
link-citations: true
reference-section-title: References
---

There is sadly too little debate about if you should disallow your kid to have a smartphone.
This is an important discussion.
There are good arguments for and against it.
But most people just let their kids do whatever without thinking through it deeply.
This is dangerous and careless behavior.
You should heavily regulate what your kids are able to do to protect them, as a parent always should.
There should be no exceptions for smartphones.

I saw a post on Quora titled *[My almost 16-year-old daughter wants a smartphone. How do I get her to stop bugging me about it? She has a flip phone and that’s enough.](https://www.quora.com/My-almost-16-year-old-daughter-wants-a-smartphone-How-do-I-get-her-to-stop-bugging-me-about-it-She-has-a-flip-phone-and-that-s-enough)*
Pretty much all of the responses are exactly the same.
They are all rude, insincere, and biased.
This is what happens when almost everyone makes the same decisions with little variation about an important issue.
It creates people that are indoctrinated into a lifestyle that they think they chose themselves.
I will go through some of the most popular responses and debunk each of their arguments.

# Quora Responses

## First response

> Wow, you’re incredibly out of touch.
A smartphone has translation services, map services, general internet for everything from serious research to entertainment
>
I’m going to assume you’re a dinosaur who must’ve adopted because no way are you under 60 with such a frankly idiotic attitude.
>
The tech billionaires today are the people who’s parents bought them computers at very early ages.
>
You’re disadvantaging your daughter by falling behind and trying to hold a new person to the standard of an old and out of touch one.
>
Just buy her the stupid phone you stupid person
>
— [Spooky Boyy](https://qr.ae/pvAM6S)

The person who wrote this response did not even bother to end all of the sentences with periods.
This is undoubtedly an emotional, irrational, and lazy response.
He did not even think before laying his hands on his keyboard.
It is true that smartphones have translation and map services and access to the internet.
But you can do all of those things on a computer.
I do not consider smartphones to be computers.
On computers, you can create great things and you can consume great things.
On smartphones, you cannot create anything worth using.
And there is nothing worth consuming on a smartphone either.

You did not have to personally attack the person who asked an honest question by calling them a "dinosaur."
You should not be experiencing genuine anger over the fact that someone parents differently than you.
And since you are personally attacking someone, you should not be surprised to be personally attacked yourself.
You cannot even write proper sentences with proper line spacing.
Who is the dinosaur now?

"Just buy her the stupid phone you stupid person."
I like the wording in this sentence.
"**Just** buy her the **stupid** phone you stupid person."
To me, it is obvious why he chose this specific wording.
He does not want unique people to exist, and to him a smartphone is a way to prove you are just like everyone else.
He calls it a "stupid" phone because he does not think that it is something that should be valued.
It is viewed as a *necessity*: something that is required—like food.
And the modern smartphone is bought again constantly as if it is similar to groceries.
It will be bought and thrown away, year after year, over and over again as if it is a cheap physiological need that we are entitled to.

## Second response

> Your such a good parent. It'd be a shame if your daughter did something crazy, like, acquired a skillet that's impossible to function in society without today. You wouldn't want that would you? Your daughter to succeed in life? Oh God, what a horror that would be!
>
I'm sorry, others are trying to be nice here. Not me, I'm not going to sugar coat anything. You're a terrible parent who's trying your hardest to ensure your daughter doesn't succeed in life. Your daughter is not the problem, and you should be arrested.
>
— [Seven Star Vapor](https://qr.ae/pvAw1r), PhD Evolutionary Biology & Ecology, Purdue University (2019)

Why do all of these responses have terrible spelling, grammar, and general typography?
I did not cherry pick any responses.
These are the most popular responses.
This means that these are the ones with the most likes and comments.
First of all, it is *you're*, **not** *your*.
Do not put a comma after the word *like*.
Use the word *learned* instead of *acquired*.
How could you misspell *skill* as "skillet?"
That is outright embarrassing.

The poor spelling, grammar, and typography is a clear symptom of being emotional.
This person was extremely emotional when typing this response, making him unable to type properly.
This is important to point out because it shows the common theme and problem with smartphone users.
They vapidly consume something that they know is wrong to consume; they do it anyway.
How could anyone who is addicted to their smartphone give a rational response to a question like this?
It is logically impossible.

This person wants to paint a clear picture.
The picture that this parent is conspiring to stop his daughter from succeeding in life.
This cannot be true though, as this parent clearly wants what is best for her.
A good parent will place restrictions where it is necessary, even when it is controversial to do so.
A bad parent or a *[free-range parent](https://www.urbandictionary.com/define.php?term=Free%20Range%20Parents)* is too cowardly to look their kids in their eyes and tell them "no."
It is important to say "no" sometimes.

There are no skills that you can acquire from a smartphone.
That is the reality we must face.
Smartphones are devices made purely for consumption.
It is completely possible to function on society without a smartphone.
I do it every single day.
I live life not using a smartphone like a normal person because there is nothing productive you can do on a smartphone.
"You should be arrested."
How dare you say that to someone for caring about their kid?
This is a generally rude and irrational response.
Anyone outside of his cult can notice this.

## Third response

> Your daughter is probably feeling left out as her friends probs all have smart phones with social media etc. There are smart phones that are under £100 so you should tell her she has to earn it doing a jobs and put the money in savings account maybe? A flip phone? Im on your daughter's side becos she's probs embarrassed about. I got my first smart over 10yrs ago and before that I had basic phones cos there wasn't many out there yet. Tell your daughter she needs to stop bugging you and earn it. There are some good smart phones out there under £100 that are just as good as ones that are over 200+!!!
>
— [Abbie Carey Williams](https://qr.ae/pvAwtw), former Nursery Practitioner at ... (2011-2016)

I cannot help but notice that most of these responses are so poorly written!
Was this one written by a nine-year-old?
Anyways, I appreciate that this response is actually reasonable, unlike the first two.
Despite it being reasonable, I disagree with it.
This response is focusing on something that is irrelevant to the original question.

Social media is usable on real computers.
But you should also restrict your kids' social media usage.
I am glad that she recommended earning it though, unlike other comments which suggested to just give it to her.

## Fourth response

> That's not enough for a kid today. Plain and simple. Their social life happens online, school work happens online. For my kids a smartphone is obligatory for school… All information is shared through an app.
>
So refusing her a proper smartphone seems like borderline negligence to me.
>
— [Kas Van Dam](https://qr.ae/pvAwvT), Master from Master of Arts

Neither social life nor school work needs to happen online.
Most kids' social life are by actual socializing in school.
You do not need social media to socialize.
School work is usually printed, but schools are shifting toward online work.
That does not justify the usage of a smartphone.
Like I said before, working on a smartphone is impossible.
You should buy her a laptop if you can.
The school must allow her to borrow one if you cannot afford one.
I still think that most online work is unjustified.
That is a topic for another article though.

Also, if I have to hear about another one of these degenerate "apps" again.
Pronounce the full word, it is *application*.
Schools have no right to force you to share your data over a proprietary application.
That is downright immoral and a breach of privacy.
Students have the right to reject the use of said applications.
Finally, not buying your kid a smartphone is not negligence.
*Negligence* is failure to take proper care over something.
Nothing shows proper care quite like doing what is best for your children.

# Conclusion

You might conclude thinking that you should disallow your kids from having a smartphone.
But that is not actually the message I am trying to convey.
The message I am trying to convey is to actually heavily regulate the way your kids use technology.
The people that I responded to in this article think the opposite.
They think that it is okay to have technology raising children.
I think that that is egregious.
Parents are responsible for raising their kids, and that means placing reasonable restrictions and saying "no" whenever necessary.

Personally, I will allow my kids to use a smartphone, but I will teach them to not to be dependent on them.
Generally in life, you should avoid dependencies.
Dependencies are bad because once that dependency is taken away, you cannot do anything.
I will not allow my kids to use Android or Apple smartphones, only pure Linux ones.
This seems strict, but I heavily value freedom and privacy.
Remember: raise your kids, do not let technology raise them.
